services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-desafio-shopper
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/backend
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-desafio-shopper
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
